version: '3.8'

networks:
    net:
      name: net

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./backend/mariadb_data
    

services:
  mailhog:
      image: mailhog/mailhog
      container_name: mailhog
      ports:
        - "8025:8025"  # Web UI
        - "1025:1025"  # SMTP server
      networks:
        - net
        
  web:
    build:
      context: .             # use project root, not ./nginx
      dockerfile: nginx/Dockerfile
    container_name: web
    ports:
      - "8000:80"
    depends_on:
      - mariadb
    networks:
      - net
    env_file:
      - .env_file
    volumes:
      - ./backend:/var/www/html
      - ./mail.ini:/usr/local/etc/php/conf.d/mail.ini
    
    

  mariadb:
    build: 
      context: .
      dockerfile: mariadb/Dockerfile
    container_name: mariadb-1
    ports:
      - "3306:3306"
    networks:
      - net 
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env_file

  adminer:
    image: adminer
    container_name: mariadb
    restart: always
    ports:
      - 8080:8080
    networks:
      - net
    depends_on:
      - mariadb
  

    
